Repository KSP-SpaceDock/SpaceDock, pull requests merged in 2019-08, with the labels that each got.

#225 WIP trying to make autodeploy work
  .dockerignore
  Dockerfile
  KerbalStuff/app.py
  KerbalStuff/celery.py
  KerbalStuff/config.py
  config.ini.example
  docker-compose-prod.yml
  docker-compose.yml
  logging.ini
  prepare.sh
  requirements-backend.txt
  requirements-celery.txt
  requirements.txt
  spacedock
  systemd-restart.sh
  systemd/spacedock-prepare.service
  systemd/spacedock-restart.sudoers
Labels: Priority: High, Status: In Progress, Type: Improvement

#229 Fix unpublished mods being displayed on frontend
  templates/view_profile.html
Labels: Type: Bug

#231 Fix backend dependencies and CKAN notifications in API
  KerbalStuff/blueprints/api.py
  requirements-backend.txt
  templates/view_profile.html
Labels: Priority: Low, Status: Ready, Type: Bug

#234 Make support server/channel links in footer dynamic
  KerbalStuff/app.py
  KerbalStuff/config.py
  config.ini.example
  templates/layout.html
Labels: Priority: Low, Type: Improvement

#239 Models refactoring
  KerbalStuff/blueprints/accounts.py
  KerbalStuff/blueprints/admin.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/login_oauth.py
  KerbalStuff/objects.py
  spacedock
Labels: Priority: Blocking, Status: Ready

#237 Allow crafts and flags
  templates/create.html
Labels: Priority: Low, Status: Ready
