Repository KSP-SpaceDock/SpaceDock, pull requests merged in 2020-10, with the labels that each got.

#321 Get scheme from 'protocol' config for mod download redirection to CDN
  KerbalStuff/blueprints/mods.py
  config.ini.example
Labels: Priority: High, Status: Ready, Type: Backend, Type: Bug

#322 Fix celery loglevel argument
  systemd/spacedock-celery.service
Labels: Priority: High, Status: Ready, Type: Bug

#317 Fix timeline CSS and default description check
  KerbalStuff/blueprints/mods.py
  frontend/static/css/bootstrap-theme.css
  frontend/styles/mod.scss
  frontend/styles/timeline.scss
  templates/edit_mod.html
  templates/mod.html
Labels: Priority: Normal, Status: Ready, Type: Bug, Type: Frontend

#323 α → β ❺
  Dockerfile
  KerbalStuff/app.py
  KerbalStuff/blueprints/admin.py
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/blog.py
  KerbalStuff/blueprints/lists.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/celery.py
  KerbalStuff/ckan.py
  KerbalStuff/common.py
  KerbalStuff/network.py
  KerbalStuff/objects.py
  KerbalStuff/search.py
  KerbalStuff/thumbnail.py
  README.md
  alembic/versions/2020_06_29_11_37_00-544564b4e738.py
  alembic/versions/2020_07_11_17_30_00-1aa078e0fb7e.py
  alembic/versions/2020_07_20_19_00_00-73c9d707134b.py
  config.ini.example
  frontend/Dockerfile
  frontend/coffee/edit_pack.coffee
  frontend/coffee/global.coffee
  frontend/coffee/list.coffee
  frontend/coffee/stats.coffee
  frontend/coffee/statworker.coffee
  frontend/static/css/bootstrap-theme.css
  frontend/styles/listing.scss
  frontend/styles/mod.scss
  frontend/styles/stylesheet.scss
  frontend/styles/timeline.scss
  requirements-backend.txt
  systemd/spacedock-celery.service
  templates/admin-blog.html
  templates/admin-users.html
  templates/blog.html
  templates/blog_index.html
  templates/create_list.html
  templates/edit_blog.html
  templates/edit_list.html
  templates/edit_mod.html
  templates/game.html
  templates/index.html
  templates/layout.html
  templates/mod-box.html
  templates/mod.html
  templates/mod_list.html
  templates/pack-box.html
  templates/packs.html
  templates/view_profile.html
  tests/fixtures/fake_config.py
  tests/test_api_mod.py
Labels: Priority: High, Status: Ready, Type: Bug, Type: Feature, Type: Improvement

#325 Fix service icons on logged out index
  frontend/static/css/bootstrap-theme.css
  frontend/styles/index.scss
Labels: Priority: High, Status: Ready, Type: Bug, Type: Frontend

#327 Rename spacedock-restart.sudoers to spacedock-restart_sudoers
  systemd/spacedock-restart_sudoers
Labels: Priority: Low, Status: Ready, Type: Backend, Type: Bug

#328 α → β ➏
  frontend/static/css/bootstrap-theme.css
  frontend/styles/index.scss
  systemd/spacedock-restart_sudoers
Labels: Priority: High, Type: Backend, Type: Bug, Type: Frontend

#324 β → 🜚🏭 ②
  Dockerfile
  KerbalStuff/app.py
  KerbalStuff/blueprints/admin.py
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/blog.py
  KerbalStuff/blueprints/lists.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/celery.py
  KerbalStuff/ckan.py
  KerbalStuff/common.py
  KerbalStuff/network.py
  KerbalStuff/objects.py
  KerbalStuff/search.py
  KerbalStuff/thumbnail.py
  README.md
  alembic/versions/2020_06_29_11_37_00-544564b4e738.py
  alembic/versions/2020_07_11_17_30_00-1aa078e0fb7e.py
  alembic/versions/2020_07_20_19_00_00-73c9d707134b.py
  config.ini.example
  frontend/Dockerfile
  frontend/coffee/edit_pack.coffee
  frontend/coffee/global.coffee
  frontend/coffee/list.coffee
  frontend/coffee/stats.coffee
  frontend/coffee/statworker.coffee
  frontend/static/css/bootstrap-theme.css
  frontend/styles/index.scss
  frontend/styles/listing.scss
  frontend/styles/mod.scss
  frontend/styles/stylesheet.scss
  frontend/styles/timeline.scss
  requirements-backend.txt
  systemd/spacedock-celery.service
  systemd/spacedock-restart_sudoers
  templates/admin-blog.html
  templates/admin-users.html
  templates/blog.html
  templates/blog_index.html
  templates/create_list.html
  templates/edit_blog.html
  templates/edit_list.html
  templates/edit_mod.html
  templates/game.html
  templates/index.html
  templates/layout.html
  templates/mod-box.html
  templates/mod.html
  templates/mod_list.html
  templates/pack-box.html
  templates/packs.html
  templates/view_profile.html
  tests/fixtures/fake_config.py
  tests/test_api_mod.py
Labels: Priority: High, Status: Ready, Type: Bug, Type: Feature, Type: Improvement

#331 Profile forum URLs as links
  KerbalStuff/blueprints/profile.py
  templates/view_profile.html
Labels: Priority: Normal, Status: Ready, Type: Backend, Type: Frontend, Type: Improvement

#310 Chunking
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/mods.py
  frontend/build.js
  frontend/coffee/create.coffee
  frontend/coffee/update.coffee
  frontend/package-lock.json
  frontend/package.json
  frontend/static/css/bootstrap-theme.css
  frontend/styles/create.scss
  frontend/styles/update.scss
  templates/create.html
  templates/update.html
Labels: Priority: Normal, Status: Ready, Type: Backend, Type: Frontend, Type: Improvement
