Repository KSP-SpaceDock/SpaceDock, pull requests merged in 2020-06, with the labels that each got.

#271 Fix creation of new mods
  KerbalStuff/blueprints/api.py
  api.md
  frontend/coffee/create.coffee
  templates/create.html
Labels: Priority: High, Type: Backend, Type: Bug, Type: Frontend

#272 Tell JS to wait its turn
  frontend/coffee/create.coffee
Labels: Priority: High, Type: Bug, Type: Frontend

#268 Add password change option for users
  KerbalStuff/blueprints/accounts.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/profile.py
  KerbalStuff/common.py
  KerbalStuff/email.py
  emails/password-changed
  emails/password-reset
  frontend/coffee/profile.coffee
  templates/profile.html
Labels: Priority: Normal, Type: Backend, Type: Email, Type: Feature, Type: Frontend

#273 Add missing, undeclared future dependency of celery
  requirements-backend.txt
Labels: Priority: High, Type: Backend, Type: Bug, Type: Email

#278 API: Set UTC TZ for all datetimes, prune whitespace
  KerbalStuff/blueprints/api.py
  KerbalStuff/common.py
  KerbalStuff/custom_json.py
Labels: Priority: Low, Status: Ready, Type: Backend, Type: Improvement

#279 Fix support channels missing from password-changed email, and others
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/email.py
  templates/admin-links.html
  templates/game.html
Labels: Priority: Normal, Type: Backend, Type: Bug, Type: Email, Type: Frontend

#280 Add tests
  .github/workflows/pytest.yml
  .gitignore
  requirements-tests.txt
  tests/__init__.py
  tests/fake_db.py
  tests/fixtures/client.py
  tests/test_api_browse.py
  tests/test_api_mod.py
  tests/test_version.py
Labels: Priority: Low, Status: Ready, Type: Improvement

#270 Add type hints
  .github/workflows/mypy.yml
  .gitignore
  KerbalStuff/app.py
  KerbalStuff/blueprints/accounts.py
  KerbalStuff/blueprints/admin.py
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/blog.py
  KerbalStuff/blueprints/lists.py
  KerbalStuff/blueprints/login_oauth.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/blueprints/profile.py
  KerbalStuff/celery.py
  KerbalStuff/ckan.py
  KerbalStuff/common.py
  KerbalStuff/config.py
  KerbalStuff/custom_json.py
  KerbalStuff/database.py
  KerbalStuff/email.py
  KerbalStuff/helpers.py
  KerbalStuff/kerbdown.py
  KerbalStuff/network.py
  KerbalStuff/objects.py
  KerbalStuff/search.py
  KerbalStuff/thumbnail.py
  mypy.ini
Labels: Priority: Normal, Status: Ready, Type: Backend, Type: Improvement

#282 Notify CKAN after edits
  KerbalStuff/blueprints/mods.py
Labels: Priority: Low, Status: Ready, Type: Backend, Type: Improvement

#284 Return JSON after errors in /api routes
  .github/workflows/pytest.yml
  KerbalStuff/app.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/mods.py
  tests/__init__.py
  tests/fixtures/client.py
  tests/fixtures/fake_config.py
  tests/test_api_errors.py
  tests/test_errors.py
Labels: Priority: High, Type: Backend, Type: Bug

#285 α → β Ⅲ
  .github/workflows/mypy.yml
  .github/workflows/pytest.yml
  .gitignore
  KerbalStuff/app.py
  KerbalStuff/blueprints/accounts.py
  KerbalStuff/blueprints/admin.py
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/blog.py
  KerbalStuff/blueprints/lists.py
  KerbalStuff/blueprints/login_oauth.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/blueprints/profile.py
  KerbalStuff/celery.py
  KerbalStuff/ckan.py
  KerbalStuff/common.py
  KerbalStuff/config.py
  KerbalStuff/custom_json.py
  KerbalStuff/database.py
  KerbalStuff/email.py
  KerbalStuff/helpers.py
  KerbalStuff/kerbdown.py
  KerbalStuff/network.py
  KerbalStuff/objects.py
  KerbalStuff/search.py
  KerbalStuff/thumbnail.py
  emails/mod-autoupdated
  emails/mod-locked
  emails/mod-updated
  emails/password-changed
  mypy.ini
  requirements-backend.txt
  requirements-tests.txt
  templates/admin-links.html
  templates/game.html
  templates/rss-mod.xml
  tests/__init__.py
  tests/fixtures/client.py
  tests/fixtures/fake_config.py
  tests/test_api_browse.py
  tests/test_api_errors.py
  tests/test_api_mod.py
  tests/test_errors.py
  tests/test_version.py
Labels: Priority: Normal, Status: Ready

#281 Index columns used for order_by
  KerbalStuff/objects.py
  alembic/versions/2019_08_29-00_40_42-6ffd5dd5efab.py
  alembic/versions/2019_08_29_01_09_04-77f76102f99c.py
  alembic/versions/2020_05_15_13_41_11-7993492be4eb.py
  alembic/versions/2020_06_16_00_05_40-d6f41a805840.py
Labels: Priority: Low, Status: Ready, Type: Backend, Type: Improvement

#277 Precalculate mod scores in periodic celery background task
  KerbalStuff/blueprints/accounts.py
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/celery.py
  KerbalStuff/common.py
  KerbalStuff/objects.py
  KerbalStuff/search.py
  alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
  docker-compose-prod.yml
  docker-compose.yml
  systemd/spacedock-celery.service
Labels: Priority: Normal, Type: Backend, Type: Improvement

#286 Return ModVersion downloads in API
  KerbalStuff/blueprints/api.py
  KerbalStuff/objects.py
  tests/test_api_mod.py
Labels: Priority: Low, Type: Improvement

#288 Admin page fixes
  KerbalStuff/blueprints/admin.py
  templates/admin-game-versions.html
  templates/admin-games.html
  templates/admin-publishers.html
  templates/admin.html
Labels: Priority: Low, Status: Ready, Type: Frontend, Type: Improvement

#290 Give new foreign key in 7993492be4eb a name to make downgrades work
  .github/workflows/mypy.yml
  alembic/env.py
  alembic/versions/2020_05_15_13_41_11-7993492be4eb.py
  alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
  alembic/versions/alembic.pyi
Labels: Priority: Normal, Status: Ready, Type: Backend, Type: Bug

#287 Score penalties for incompatible mods
  KerbalStuff/search.py
  alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
  requirements-backend.txt
Labels: Priority: Normal, Status: Need Feedback, Status: Ready, Type: Backend, Type: Improvement

#299 Don't require smtp-user and -password to be set in send_mail()
  KerbalStuff/celery.py
Labels: Priority: Blocking, Status: Ready, Type: Bug, Type: Email

#300 α → β Ⅳ
  .github/workflows/mypy.yml
  KerbalStuff/blueprints/accounts.py
  KerbalStuff/blueprints/admin.py
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/celery.py
  KerbalStuff/common.py
  KerbalStuff/objects.py
  KerbalStuff/search.py
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/2019_08_29-00_40_42-6ffd5dd5efab.py
  alembic/versions/2019_08_29_01_09_04-77f76102f99c.py
  alembic/versions/2020_05_15_13_41_11-7993492be4eb.py
  alembic/versions/2020_06_16_00_05_40-d6f41a805840.py
  alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
  alembic/versions/alembic.pyi
  docker-compose-prod.yml
  docker-compose.yml
  requirements-backend.txt
  systemd/spacedock-celery.service
  templates/admin-game-versions.html
  templates/admin-games.html
  templates/admin-publishers.html
  templates/admin.html
  tests/test_api_mod.py
Labels: Priority: Blocking, Status: Ready

#302 Run db.commit() before calculating mod.score in update_mod()
  KerbalStuff/app.py
  KerbalStuff/blueprints/api.py
  spacedock
Labels: Priority: Blocking, Status: Ready, Type: Backend, Type: Bug

#304 Copy get_mod_score instead of importing it
  alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
Labels: Priority: Blocking, Status: Ready, Type: Bug

#305 Zero score for mods without default versions
  KerbalStuff/search.py
  alembic/versions/2020_06_23_17_49_36-85be165bc5dc.py
Labels: Priority: Blocking, Type: Bug

#306 Don't join mod_search to ModVersions
  KerbalStuff/search.py
Labels: Priority: Blocking, Status: Ready, Type: Backend, Type: Bug

#307 Remove download count from mod version api again
  KerbalStuff/blueprints/api.py
  tests/test_api_mod.py
Labels: Priority: High, Status: Ready, Type: Backend, Type: Bug
