Repository KSP-SpaceDock/SpaceDock, pull requests merged in 2020-05, with the labels that each got.

#252 Fix download_path being saved absolute in the database
  KerbalStuff/blueprints/api.py
Labels: Priority: Blocking, Status: Ready, Type: Bug

#257 Check if mod is published in CKAN triggers
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/ckan.py
Labels: Priority: Low, Status: Ready, Type: Backend, Type: Bug

#255 Catch and display upload errors
  Dockerfile
  KerbalStuff/blueprints/api.py
  frontend/Dockerfile
  frontend/coffee/update.coffee
Labels: Priority: Normal, Type: Backend, Type: Bug, Type: Frontend

#261 Don't break profile page if a mod has no default_version
  KerbalStuff/blueprints/profile.py
  templates/mod-box.html
Labels: Priority: Normal, Status: Ready, Type: Backend, Type: Bug, Type: Frontend

#260 [Feature] Ability for admins to lock mods
  KerbalStuff/blueprints/mods.py
  KerbalStuff/celery.py
  KerbalStuff/email.py
  KerbalStuff/objects.py
  alembic/versions/2020_05_15_13_41_11-7993492be4eb.py
  emails/confirm-account
  emails/grant-notice
  emails/mod-autoupdated
  emails/mod-locked
  emails/password-reset
  frontend/coffee/global.coffee
  spacedock
  templates/mod.html
Labels: Priority: Normal, Status: Ready, Type: Backend, Type: Email, Type: Feature, Type: Frontend

#263 Work around over-eager adblockers hiding stuff they shouldn't hide
  frontend/coffee/global.coffee
  templates/featured-mod-box.html
  templates/mod.html
  templates/mod_list.html
Labels: Priority: Normal, Status: Ready, Type: Frontend, Type: Improvement

#265 Send UTC TZ for mod creation timestamps
  KerbalStuff/blueprints/api.py
Labels: Priority: Low, Status: Ready, Type: Backend, Type: Improvement

#266 Restore sponsor button on GitHub
  .github/FUNDING.yml
Labels: Priority: Low, Status: Ready, Type: Improvement

#262 Rework the admin area
  KerbalStuff/blueprints/admin.py
  templates/admin-blog.html
  templates/admin-email.html
  templates/admin-game-versions.html
  templates/admin-games.html
  templates/admin-links.html
  templates/admin-page-nav.html
  templates/admin-publishers.html
  templates/admin-users.html
  templates/admin.html
  templates/layout.html
Labels: Priority: Normal, Status: Ready, Type: Backend, Type: Feature, Type: Frontend

#245 Show short mod abstract on mod page
  docker-compose.yml
  frontend/styles/listing.scss
  frontend/styles/stylesheet.scss
  templates/edit_mod.html
  templates/mod.html
Labels: Priority: Low, Type: Frontend, Type: Improvement

#259 Remove old links from navbar dropdown
  KerbalStuff/blueprints/api.py
  README.md
  systemd/spacedock-notify.service
  systemd/spacedock.target
  templates/layout.html
Labels: Priority: Low, Status: Ready, Type: Frontend, Type: Improvement

#264 Fix default game fallback in _restore_game_info
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/common.py
  frontend/coffee/create.coffee
  templates/create.html
Labels: Priority: Low, Type: Backend, Type: Bug, Type: Frontend
