Repository KSP-SpaceDock/SpaceDock, pull requests merged in 2021-07, with the labels that each got.

#365 Fewer modpacks per page, hide modpacks without mods
  KerbalStuff/blueprints/lists.py
Labels: Area: Backend, Priority: Low, Status: Ready

#364 Allow http or nothing in forum links
  KerbalStuff/blueprints/profile.py
  templates/view_profile.html
Labels: Area: Backend, Priority: Low, Status: Ready, Type: Bug

#369 Let users choose which emails to receive
  KerbalStuff/blueprints/profile.py
  KerbalStuff/email.py
  KerbalStuff/objects.py
  alembic/versions/2021_06_28_19_00_00-17fbd4ff8193.py
  alembic/versions/alembic.pyi
  frontend/coffee/profile.coffee
  frontend/styles/mod.scss
  templates/profile.html
Labels: Area: Backend, Area: Email, Area: Frontend, Area: Migration, Priority: Normal, Status: Ready, Type: Feature

#367 Add long description to mod creation page
  KerbalStuff/blueprints/api.py
  frontend/coffee/create.coffee
  frontend/styles/create.scss
  templates/create.html
Labels: Area: Backend, Area: Frontend, Priority: Normal, Status: Ready, Type: Feature

#354 Eliminate anonymous session cookies
  KerbalStuff/app.py
  KerbalStuff/middleware/session_interface.py
Labels: Area: Backend, Priority: Normal, Status: Need Feedback, Status: Ready, Type: Improvement

#378 Handle missing default mod version, don't close db before rendering templates
  .github/workflows/mypy.yml
  .github/workflows/pytest.yml
  KerbalStuff/app.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/ckan.py
  KerbalStuff/common.py
  KerbalStuff/config.py
  KerbalStuff/email.py
  KerbalStuff/stubs/jinja2.pyi
  requirements-backend.txt
  templates/layout.html
  templates/mod.html
Labels: Area: Backend, Priority: Low, Status: Ready, Type: Bug

#357 Allow editing names of mods and modpacks
  KerbalStuff/blueprints/lists.py
  KerbalStuff/blueprints/mods.py
  templates/edit_list.html
  templates/edit_mod.html
  templates/mod_list.html
Labels: Area: Backend, Area: Frontend, Priority: Normal, Status: Ready, Type: Feature

#377 Run database migrations after pulling changes
  KerbalStuff/celery.py
  KerbalStuff/objects.py
  alembic/versions/2021_06_28_19_00_00-17fbd4ff8193.py
Labels: Area: Backend, Area: Migration, Priority: Low, Status: In Progress, Status: Need Feedback, Type: Improvement, Type: Question

#374 Unify storage base path and fix background image URLs
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/blueprints/profile.py
  KerbalStuff/common.py
  KerbalStuff/email.py
  KerbalStuff/objects.py
  KerbalStuff/thumbnail.py
  alembic/versions/2021_07_29_18_00_833ba1ee8c72.py
  docker-compose.yml
  frontend/coffee/edit_mod.coffee
  frontend/coffee/profile.coffee
  frontend/configs/nginx.nginx
  spacedock
  templates/create.html
  templates/edit_mod.html
  templates/layout.html
  templates/mod-box.html
  templates/mod.html
  templates/profile.html
  templates/view_profile.html
Labels: Area: Backend, Area: Migration, Priority: Normal, Type: Bug
