Repository KSP-SpaceDock/SpaceDock, pull requests merged in 2021-08, with the labels that each got.

#384 Modernize Youtube embeds and exempt from Bleach cleaning, abandon Imgur embeds
  KerbalStuff/common.py
  KerbalStuff/kerbdown.py
  templates/markdown.html
Labels: Type: Bug, Area: Backend, Priority: Normal, Status: Ready

#385 Add OpenGraph meta tags
  KerbalStuff/app.py
  config.ini.example
  templates/game.html
  templates/layout.html
  templates/mod.html
  templates/mod_list.html
  templates/view_profile.html
Labels: Priority: Low, Type: Feature, Area: Frontend

#386 Update frontend dependencies
  frontend/package-lock.json
  frontend/package.json
Labels: Type: Improvement, Priority: Normal, Status: Ready, Area: Frontend, dependencies

#380 Fix attribute error when saving mod that was in deleted modpack
  KerbalStuff/objects.py
  alembic/versions/2021_07_29_18_00_00-833ba1ee8c72.py
  alembic/versions/2021_07_30_16_16_44-1cbfc1acd83d.py
Labels: Type: Bug, Area: Backend, Priority: Blocking, Status: Ready, Area: Migration

#381 User profile fields for KerbalX and GitHub
  KerbalStuff/blueprints/profile.py
  KerbalStuff/objects.py
  alembic/versions/2021_07_30_17_19_03-3fb8a6e2e0a5.py
  frontend/coffee/profile.coffee
  frontend/styles/mod.scss
  templates/profile.html
  templates/view_profile.html
Labels: Area: Backend, Priority: Normal, Type: Feature, Status: Ready, Area: Migration

#388 Escape mod name in mod pack typeahead
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/profile.py
  frontend/coffee/edit_pack.coffee
Labels: Type: Bug, Area: Backend, Priority: High, Status: Ready
