Repository KSP-SpaceDock/SpaceDock, pull requests merged in 2023-04, with the labels that each got.

#483 Fix changelog editing for co-authors
  KerbalStuff/blueprints/mods.py
Labels: Type: Bug, Area: Backend, Priority: High, Status: Ready, Scope: Trivial

#482 β → 🜚🏭 Ⅶ
  .gitattributes
  KerbalStuff/antivirus.py
  KerbalStuff/blueprints/admin.py
  KerbalStuff/blueprints/anonymous.py
  KerbalStuff/blueprints/api.py
  KerbalStuff/blueprints/lists.py
  KerbalStuff/blueprints/mods.py
  KerbalStuff/celery.py
  KerbalStuff/ckan.py
  KerbalStuff/common.py
  KerbalStuff/config.py
  KerbalStuff/notification.py
  KerbalStuff/objects.py
  KerbalStuff/search.py
  KerbalStuff/thumbnail.py
  alembic/versions/2023_03_14_18_49_21-b9e4c97b74c1.py
  alembic/versions/2023_03_20_12_00_00-7eec82634342.py
  alembic/versions/2023_03_20_16_00_00-f7d352d49c2b.py
  alembic/versions/alembic.pyi
  api.md
  config.ini.example
  frontend/coffee/admin-users.coffee
  frontend/coffee/create.coffee
  frontend/coffee/edit_pack.coffee
  frontend/coffee/game.coffee
  frontend/coffee/profile.coffee
  frontend/styles/listing.scss
  templates/admin-notification-edit.html
  templates/admin-notifications.html
  templates/admin-users.html
  templates/admin.html
  templates/browse-list.html
  templates/create.html
  templates/create_list.html
  templates/edit_mod.html
  templates/game-box.html
  templates/game.html
  templates/index.html
  templates/layout.html
  templates/mod-box.html
  templates/mod.html
  templates/packs.html
  templates/profile.html
  templates/view_profile.html
  tests/fixtures/fake_config.py
  tests/test_api_mod.py
Labels: Type: Bug, Type: Improvement, Area: Backend, Priority: Normal, Type: Feature, Status: Ready, Area: Frontend, Area: Migration, Scope: Large, Status: Waiting

#490 Send co-authors to CKAN as POST form lists
  KerbalStuff/notification.py
  KerbalStuff/objects.py
Labels: Type: Bug, Area: Backend, Priority: Normal, Status: Ready, Scope: Medium

#491 Show how many mods use each notification
  KerbalStuff/objects.py
  templates/admin-notifications.html
Labels: Type: Improvement, Area: Backend, Priority: Low, Status: Ready, Scope: Trivial

#493 Preserve admin user search after user deletion
  KerbalStuff/blueprints/admin.py
  templates/admin-users.html
Labels: Type: Bug, Area: Backend, Priority: Low, Status: Ready, Scope: Trivial

#495 Fix admin user deletion on profile
  KerbalStuff/blueprints/api.py
  frontend/coffee/profile.coffee
  templates/view_profile.html
Labels: Type: Bug, Area: Backend, Priority: Low, Status: Ready, Area: Frontend, Scope: Medium

#492 Show add-mod button instead of empty game sections
  KerbalStuff/blueprints/anonymous.py
  templates/game.html
Labels: Area: Backend, Priority: Normal, Type: Feature, Status: Ready, Scope: Medium

#494 Add Steam, Discord, and Youtube to profile
  KerbalStuff/blueprints/profile.py
  KerbalStuff/objects.py
  alembic/versions/2023_04_08_19_02_56-ba0c9afb6cb0.py
  frontend/coffee/profile.coffee
  templates/admin-users.html
  templates/profile.html
  templates/view_profile.html
Labels: Area: Backend, Priority: Low, Type: Feature, Status: Ready, Area: Frontend, Area: Migration, Scope: Medium

#497 Make sure JNO versions aren't empty
  KerbalStuff/notification.py
Labels: Type: Improvement, Area: Backend, Priority: Normal, Status: Ready, Scope: Trivial

#498 Support tables in markdown
  KerbalStuff/common.py
  KerbalStuff/kerbdown.py
  requirements-backend.txt
Labels: Area: Backend, Priority: Normal, Type: Feature, Status: Ready, Scope: Medium

#496 Remove extra margin-top from h3 styles
  frontend/styles/index.scss
Labels: Status: In Progress, Area: Frontend
